### ISSUE TITLE
Option to share a set of files

### ISSUE THREAD

**Issue by unkaktus** [nogoegst/onionize#3]
Do it in tar-ish way?

**Comment by nogoegst** [comment]
Can be done by implementing custom http.FileSystem

**Comment by lostinblue** [comment]
There is a tar archive fs, that may work for this. 

Awsome project btw

**Comment by unkaktus** [comment]
tar does not work for random access (that's why zip is here). By tar way I mean arguments -
 something like
`onionize file1 file2 file3 ... `.

Thanks.

**Comment by unkaktus** [comment]
Implemented in 5a20e104dc21230777623d6965f0d629f0fc8cd6,
