### ISSUE TITLE
could not determine kind of name for C.gtk_menu_popup_at_pointer

### ISSUE THREAD

**Issue by ei8fdb** [nogoegst/onionize#44]
Hi!

I'm having a problem with getting onionize installed.

OS: 
Ubuntu 16.04.3 LTS 64-bit

GTK:   
Installed: 2.24.30-1ubuntu1.16.04.2
Installed: 3.18.9-1ubuntu3.3

STEPS
I've got the GO PATH set:
`bernard@MACHINE:~$ export GOPATH=$HOME/go
bernard@MACHINE:~$ export PATH=$PATH:$GOROOT/bin:$GOPATH/bin`

When I try to install:
`bernard@MACHINE:~$ go get -tags gui github.com/nogoegst/onionize/cmd/onionize`

I first get these 2 messages:
`# github.com/nogoegst/onionize/vendor/github.com/nogoegst/tlspin
go/src/github.com/nogoegst/onionize/vendor/github.com/nogoegst/tlspin/tlspin.go:23: undefined: tls.X25519
go/src/github.com/nogoegst/onionize/vendor/github.com/nogoegst/tlspin/tlspin.go:26: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305`

Then this:
`# github.com/nogoegst/onionize/vendor/github.com/gotk3/gotk3/gtk
could not determine kind of name for C.gtk_menu_popup_at_pointer
bernard@MACHINE:~$`

I'm unsure how to proceed.
Thanks.

**Comment by unkaktus** [comment]
Hi @ei8fdb!

You seems to have old Golang version installed. I completely forgot to mention this in the readme, sorry!
Details: It uses X25519 ciphersuite for TLS which support appeared in Go 1.8.

**Comment by unkaktus** [comment]
Thank you!

**Comment by ei8fdb** [comment]
Hea @nogoegst,

OK, I've removed Golang which was installed from standard repositories, and replaced it with 1.9.3, but I still have the same issue as above.

**OS**
same as above

**Golang version**
```
bernard@MACHINE:~$ go version
go version go1.9.3 linux/amd64
```

Attempt to install onionize
```
bernard@MACHINE:~$ go get -u -tags gui github.com/nogoegst/onionize/cmd/onionize
# github.com/nogoegst/onionize/vendor/github.com/gotk3/gotk3/gtk
go/src/github.com/nogoegst/onionize/vendor/github.com/gotk3/gotk3/gtk/
menu_since_3_22.go:18:2: could not determine kind of name for 
C.gtk_menu_popup_at_pointer
```

This is the same issue as I had previously above.

Any suggestions? Thanks.
