### ISSUE TITLE
Why seperate file selection in dropdown?

### ISSUE THREAD

**Issue by ei8fdb** [nogoegst/onionize#45]
Hi!

I'm looking at the GUI on an OS X computer. I see in the file selection drop-down options for a "zip file" ([link to GUI screenshot](https://github.com/nogoegst/onionize/blob/master/docs/onionize-zip-1.png)), and for non-zip file "file"([link to GUI screenshot](https://github.com/nogoegst/onionize/blob/master/docs/onionize-file-1.png)).

Why is there an option for these 2? A zipfile, is a file. 

Is there some technical constraint?

Thanks!

**Comment by unkaktus** [comment]
The "zip file" option (now called "contents of zip") is the option to serve contents of a zip 
 file and not the file itself.
It was fixed in 2f061bb. You can update `onionize` via
```
go get -u -tags gui github.com/nogoegst/onionize/cmd/onionize
```

Also thanks for the reminder of #37 - screenshots do not reflect real interface anymore and should be updated.

**Comment by ei8fdb** [comment]
Thanks @nogoegst.

**Comment by unkaktus** [comment]
Thank you for the report! :beers:
